[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello_world"
path = "src/main.rs"

[dependencies]
userspace-runtime = { path = "../../runtime" }

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release] 
panic = "abort"
opt-level = "s"
lto = true